name: Builds, tests & co

on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-15            # macOS arm64
          - macos-15-intel      # macOS x64
        ocaml-compiler:
          - "5"
        include:
          - os: ubuntu-latest
            ocaml-compiler: "4"
          - os: macos-15
            ocaml-compiler: "4"
          - os: macos-15-intel
            ocaml-compiler: "4"
          - os: windows-latest
            ocaml-compiler: "4"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5"
      - uses: ocaml/setup-ocaml/lint-doc@v3
      - uses: ocaml/setup-ocaml/lint-fmt@v3
